// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0T-j9YxgL9_kAB_Z-jWQfPeNX1hLiMfE',
    appId: '1:405740710757:web:160042e28e94b62b540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    authDomain: 'my-first-project-9ad78.firebaseapp.com',
    storageBucket: 'my-first-project-9ad78.firebasestorage.app',
    measurementId: 'G-W18QEY83P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0jviX6ea7a3somapYtbYCnsuKL6BfJuI',
    appId: '1:405740710757:android:d5e5b9ba39877f99540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    storageBucket: 'my-first-project-9ad78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASOfPvpZ-B7I1tYSN266sX2KsNORl-ahY',
    appId: '1:405740710757:ios:0f0d33e60e07d9fa540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    storageBucket: 'my-first-project-9ad78.firebasestorage.app',
    androidClientId: '405740710757-c4v429cktitgr43jl8gvrqoa1jdo0vjo.apps.googleusercontent.com',
    iosClientId: '405740710757-leeqsbt4gv9kj4429p6ljtuavai04r6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepLinking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMiVrDM94P1ylE3G5iugQLEmuLoev4M8',
    appId: '1:405740710757:web:12c6d743e955acf0540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    authDomain: 'my-first-project-9ad78.firebaseapp.com',
    storageBucket: 'my-first-project-9ad78.firebasestorage.app',
    measurementId: 'G-45ZGR9P0NE',
  );
}
